spring.application.name=textilecad

# База данных
spring.datasource.url=jdbc:mysql://localhost:3306/textilecad
spring.datasource.username=user
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Настройки HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=localhost

# JWT
security.jwt.secret-key=2f4c4185d57cb195406dd3ca79d868e123a88067384c81186af986910ba434d6
security.jwt.expiration-time=3600000

# Почта
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alesialoika.bsuir@gmail.com
spring.mail.password=zwrttylvfndaeemj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# URL фронтенда для генерации ссылки на сброс пароля и время жизни токена для сброса пароля
app.frontend.url=https://localhost:5173
app.password-reset.token-lifetime-minutes=15

# Логирование почты
logging.level.org.springframework.mail=DEBUG